libpqxx: pqxx::tablereader Class Reference
pqxx::tablereader Class Reference
#include <tablereader.hxx>
Public Member Functions
tablereader (transaction_base &, const std::string &Name, const std::string &Null=std::string())
template<typename ITER >
tablereader (transaction_base &, const std::string &Name, ITER begincolumns, ITER endcolumns)
template<typename ITER >
tablereader (transaction_base &, const std::string &Name, ITER begincolumns, ITER endcolumns, const std::string &Null)
~tablereader () throw ()
template<typename TUPLE >
tablereader & operator>> (TUPLE &)
operator bool () const throw ()
bool operator! () const throw ()
bool get_raw_line (std::string &Line)
template<typename TUPLE >
void tokenize (std::string, TUPLE &) const
virtual void complete ()
Detailed Description
Deprecated:
Efficiently pull data directly out of a table.
Warning:
This class does not work reliably with multibyte encodings. Using it with some multi-byte encodings may pose a security risk.
Constructor & Destructor Documentation
pqxx::tablereader::tablereader (transaction_base & T, const std::string & Name, const std::string & Null = std::string())
template<typename ITER > pqxx::tablereader::tablereader (transaction_base & T, const std::string & Name, ITER begincolumns, ITER endcolumns)
References pqxx::tablestream::columnlist().
template<typename ITER > pqxx::tablereader::tablereader (transaction_base & T, const std::string & Name, ITER begincolumns, ITER endcolumns, const std::string & Null)
References pqxx::tablestream::columnlist().
pqxx::tablereader::~tablereader () throw ()
Member Function Documentation
void pqxx::tablereader::complete () [virtual]
Implements pqxx::tablestream.
bool pqxx::tablereader::get_raw_line (std::string & Line)
Referenced by pqxx::tablewriter::operator<<().
pqxx::tablereader::operator bool () const throw ()
bool pqxx::tablereader::operator! () const throw ()
template<typename TUPLE > tablereader & pqxx::tablereader::operator>> (TUPLE & T)
template<typename TUPLE > void pqxx::tablereader::tokenize (std::string Line, TUPLE & T) const
The documentation for this class was generated from the following files:
tablereader.hxx
tablereader.cxx